# Generated by Django 2.2.1 on 2019-05-29 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchDetails',
            new_name='SearchDetail',
        ),
    ]
