# Generated by Django 2.2.1 on 2019-05-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20190529_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdetail',
            name='query',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
